extends: 'eslint:recommended'
parserOptions:
  sourceType: module
env:
  es6: true
  node: true
globals:
  atom: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
